language: python
branches:
    only:
        - master
        - /^\d\.\d+$/

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=pypy
    - python: 3.4
      env: TOXENV=py34
    - python: 3.6
      env: TOXENV=py36

install:
- pip install -U tox
script: tox
